SHOP/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:type>/<slug:filter_slug>/', views.product_list, name='product_list_by_'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

SHOP_APP/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('catalog/', include(('SHOP.urls', 'SHOP'), namespace='shop')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    url('social-auth/', include(('social_django.urls', 'social-auth'), namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

customers/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^profile/$', views.profilepage, name='profile'),
    # url(r'^login/$', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^password-change/$', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    url(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    url(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

SHOP/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class HashTag(models.Model):
    hash_tag = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = 'Хэш-тег'
        verbose_name_plural = 'Хэш-теги'

    def __str__(self):
        return self.hash_tag


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='category/%Y/%m/%d', blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_',
                       args=['category', self.slug])


class Type(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='type/%Y/%m/%d', blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_',
                       args=['type', self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='brand/%Y/%m/%d', blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_',
                       args=['brand', self.slug])


class Product(models.Model):
    hash_tag = models.ManyToManyField(HashTag, related_name='tags', db_index=True, blank=True, null=True )
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, db_index=True)
    category = models.ManyToManyField(Category)
    type = models.ManyToManyField(Type)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    name = models.CharField(max_length=200, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, db_index=True)
    description = models.TextField(blank=True, db_index=True)
    composition = models.CharField(max_length=200, db_index=True, blank=True)
    stock = models.PositiveIntegerField(blank=True, null=True, db_index=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)

    class Meta:
        ordering = ('name', 'created', 'updated', 'stock', 'price')
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

SHOP/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from .models import Category, Type, Brand, Product, HashTag
from cart.forms import CartAddProductForm


def product_list(request, type=None, filter_slug=None):
    category = None
    ttype = None
    brand = None
    categories = Category.objects.all()
    types = Type.objects.all()
    brands = Brand.objects.all()
    products = Product.objects.filter(stock__gt=0)
    if type == 'category':
        category = get_object_or_404(Category, slug=filter_slug)
        products = products.filter(category=category)

    if type == 'type':
        ttype = get_object_or_404(Type, slug=filter_slug)
        products = products.filter(type=ttype)

    if type == 'brand':
        brand = get_object_or_404(Brand, slug=filter_slug)
        products = products.filter(brand=brand)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'type': ttype,
                   'brand': brand,
                   'categories': categories,
                   'types': types,
                   'brands': brands,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, stock__gt=0)
    cart_product_form = CartAddProductForm()
    products_tags = product.hash_tag.all()
    similar_products = Product.objects.filter(hash_tag__in=products_tags).exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count('hash_tag')).order_by('-same_tags')[:4]
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form, 'similar_products':similar_products})

SHOP/templates/shop/base.html
{%  autoescape on %}
{% load static %}
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <title>{% block title %}My shop{% endblock %}</title>
            <link href="{% static "css/base.css" %}" rel="stylesheet">
        </head>
        <body>
            <div id="header">
                <a href="{% url "shop:product_list" %}" class="logo">My shop</a>
            </div>
            <div id="subheader">
                <div class="account">
                {% if request.user.is_authenticated %}
                    <a href="{% url "customers:profile" %}"><div class="account-img"><img src="{% if request.user.profile.photo %}{{ request.user.profile.photo.url }}{% else %} {% static "img/no_image.png" %}{% endif %}" alt=""></div></a>
                    <div class="buttons">
                        <a href="{% url "customers:profile" %}">View profile</a>
                        <a href="{% url "customers:logout" %}">Logout</a>
                    </div>
                {% else %}
                    <div class="buttons">
                        <a href="{% url "customers:login" %}">Log-in</a>
                    </div>
                {% endif %}
                </div>
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            In your cart:
                            <a href="{% url "cart:cart_detail" %}">
                                {{ total_items }} item{{ total_items|pluralize }},
                                {{ cart.get_total_price }} р.
                            </a>
                        {% else %}
                            Your cart is empty.
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">
                                {{ message|safe }}
                                <a href="#" class="close">x</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <div id="content">
                {% block content %}{% endblock %}
            </div>
        </body>
    </html>
{% endautoescape %}